[tool.poetry]
name = "VeloCT"
version = "0.1.0"
description = ""
authors = ["Sushant Dinesh <sushant.dinesh94@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "==3.12.*"
asyncio = "^3.4.3"
cvc5 = "^1.2.0"
pyyaml = "^6.0.2"
loguru = "^0.7.2"
typer = "^0.12.5"
typing-extensions = "^4.12.2"
redis = "^5.0.8"
motor = "^3.5.1"
lark = "^1.2.2"
networkx = "^3.4.2"
more-itertools = "^10.5.0"
vcdvcd = "^2.3.6"
ray = {extras = ["default"], version = "^2.44.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = [
  "."
]
markers = [
    "expr"
]
